[package]
name = "rusty_naccess"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"    # For better error handling
clap = "4.4"         # For command line argument parsing
phf = { version = "0.11.2", features = ["macros"] }
pdbtbx = "0.12.0"     # For PDB file handling
